// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLASk0HMVqe96ny7_9iiv6y0lGE1wjeYs',
    appId: '1:649575832505:web:55a3b21b30296f4c197468',
    messagingSenderId: '649575832505',
    projectId: 'phone-auth-a2a89',
    authDomain: 'phone-auth-a2a89.firebaseapp.com',
    storageBucket: 'phone-auth-a2a89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopWMHnrJBpB-3iaZRIiWod07biE1Redc',
    appId: '1:649575832505:android:46ddee7517ff908e197468',
    messagingSenderId: '649575832505',
    projectId: 'phone-auth-a2a89',
    storageBucket: 'phone-auth-a2a89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBif0iajKTc7KmzR2U8JMmmkxK2yMJxmoQ',
    appId: '1:649575832505:ios:e00f0e0c3a9afe71197468',
    messagingSenderId: '649575832505',
    projectId: 'phone-auth-a2a89',
    storageBucket: 'phone-auth-a2a89.firebasestorage.app',
    iosBundleId: 'com.example.fbintigration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBif0iajKTc7KmzR2U8JMmmkxK2yMJxmoQ',
    appId: '1:649575832505:ios:e00f0e0c3a9afe71197468',
    messagingSenderId: '649575832505',
    projectId: 'phone-auth-a2a89',
    storageBucket: 'phone-auth-a2a89.firebasestorage.app',
    iosBundleId: 'com.example.fbintigration',
  );

  static const  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLASk0HMVqe96ny7_9iiv6y0lGE1wjeYs',
    appId: '1:649575832505:web:43d8407cad4556be197468',
    messagingSenderId: '649575832505',
    projectId: 'phone-auth-a2a89',
    authDomain: 'phone-auth-a2a89.firebaseapp.com',
    storageBucket: 'phone-auth-a2a89.firebasestorage.app',
  );
}